# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKontakte' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'


  # Pods for VKontakte

  target 'VKontakteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VKontakteUITests' do
    # Pods for testing
  end

end
